course = "  pYtHoN programming  "
print(course.upper())
print(course.lower())
print(course.title())
print(course.strip())
print(course.lstrip())
print(course.rstrip())
print(course.find("pro"))
print(course.replace('p', 'j'))
print("pro" in course)
print("abc" not in course)
